defmodule HangukoWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :hanguko

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_hanguko_key",
    signing_salt: "+o+Z8n2L",
    same_site: "Lax"
  ]

  # Must match :storage_url_prefix, which is what
  # Hanguko.Audio.Storage.Local puts in front of every clip path. A
  # mismatch has no symptom but 404s.
  @audio_prefix Application.compile_env!(:hanguko, [Hanguko.Audio, :storage_url_prefix])

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # Generated audio clips, which live outside the release: in production
  # AUDIO_DIR is a mounted volume, so clips survive a redeploy instead of
  # being paid for again. Hence the MFA tuple rather than `from: :hanguko`.
  #
  # Clips are content-addressed (`Hanguko.Audio.clip_key/2`), so the bytes at
  # a URL never change and the browser can keep them for a year. Plug.Static's
  # own long-cache header applies only to URLs carrying a cache-busting query
  # string, which these don't have, so without this every play revalidates.
  plug Plug.Static,
    at: @audio_prefix,
    from: {Hanguko.Audio.Storage.Local, :root, []},
    cache_control_for_etags: "public, max-age=31536000, immutable"

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :hanguko,
    gzip: not code_reloading?,
    only: HangukoWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :hanguko
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug HangukoWeb.Router
end
